### ISSUE TITLE
Compiler errors with logger level VERBOSE

### ISSUE THREAD

**Issue by repiuk** [jodur/ESPHOME-ITHO#1]
If enable logging

logger:
  level: VERBOSE #Enable this line to find out the ID of youre remote

The compiler drops errors like:
/root/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/WString.h:39:34: error: initializer fails to determine size of '__c'

Any other trick to find the ID's of my remotes?

**Comment by jodur** [comment]
Sorry i never tested this, because i already now my Id. Latest commit should resolve youre problem. Please provide feedback so i could close this issue

**Comment by repiuk** [comment]
Thanks! Compiles without errors and I see lots of ID's. Some trial and error should solve that.
