### ISSUE TITLE
OTA does not work

### ISSUE THREAD

**Issue by ualex73** [jodur/ESPHOME-ITHO#3]
After flashing the code with ESPHome, it is not possible to upload new firmware via OTA. Via serialport it works, because it resets the ESP8266 before it uploads the new firmware.

According to the following link, the Tickers is the problem:
https://gathering.tweakers.net/forum/view_message/63513496

**Comment by ualex73** [comment]
Opened a PR with a workaround for the OTA problem #5

**Comment by jodur** [comment]
Issue resolved. Intterupt is now disabled during OTA
