### ISSUE TITLE
Regular crashes ESP8266

### ISSUE THREAD

**Issue by ualex73** [jodur/ESPHOME-ITHO#4]
With the ESPHome Itho code it seems the ESP8266 regularly crashes, because i see uptimes of 600-700 seconds regulary when i check the logging.

Anything i can debug?

**Comment by ualex73** [comment]
For now, i will close it ... I noticed something in the logging ;-)

**Comment by Michaeldiy** [comment]
@ualex73 what was the problem whit your setup. I have the same problem. sometimes the wemos d1 crashes after more than a day and other times after a few hours.

**Comment by ualex73** [comment]
Oefff ... That's a long time ago, I *think* my mistake was a missing Home Assistant connection (timeout is 600 seconds) ... Then ESPHome reboots by itself.

**Comment by Michaeldiy** [comment]
Yes I have a few more that just work well. I had the same problem with espeasy on a Nodemcu. @jodur is this a known issue for you?
