### ISSUE TITLE
ESP stuck when flashing

### ISSUE THREAD

**Issue by xorob0** [jodur/ESPHOME-ITHO#6]
Hi, first of all thanks for this project, I greatly appreciate it.

I've been trying to flash this project to my ESP's for a few week now without success.

Everything compile and the flashing process is successfull. Both when executing the `setup()` function the ESP becomes unavailable and an `ESP-XXXXXX` becomes available.
However if I flash a "normal" ESPHome project everything goes smoothly and the device is recognized almost instantly.

I've tried several ESP8266 modules including a nodeMCU, a nodeMCU v3, a D1 mini and a D1 mini pro. I think we can say it's not the ESP module.

The problem may be the C1101 modules, but when I try with nothing plugged I still got the same behavior

**Comment by fishbone-git** [comment]
same problem.  Strangely, it worked 10 days ago, but tried to do an update today and it is not possible.

**Comment by jodur** [comment]
This problem should now be solved within the latest versions. Iterrupts are now blocked during a OTA
