### ISSUE TITLE
bad indentation of a....

### ISSUE THREAD

**Issue by groofoo** [jodur/ESPHOME-ITHO#7]
so, i am fairly new to this.

i get an error in the HA config file
bad indentation of a mapping entry at line 115, column 8:
        fan: 
           ^
line 115 is the line with "    fans:" in my config file, wich i copy and pasted in my own configuration.yaml file
from youre HA_configuration.yaml file

am i doing something wrong???

[HA_configuration.txt](https://github.com/jodur/ESPHOME-ITHO/files/7548241/HA_configuration.txt)

**Comment by mories76** [comment]
Just indent line #2 two spaces that seems fine to me

**Comment by groofoo** [comment]
thx

that seems to be it.
